### ISSUE TITLE
Allow Async tasks as Actions returned by update

### ISSUE THREAD

**Issue by savuori** [fable-compiler/fable-arch#20]
This would make asynchronous tasks like ajax calls cleaner.

**Comment by mastoj** [comment]
Thanks for your feedback @savuori, but after discussing it on gitter I think I can safely close this. To achieve almost the same thing as in elm you can basically write a one line function, `let perform err succ fn = fn err succ`. If this would be added I think it makes more sense to add it to some core extension library than to fable-virtualdom.
