### ISSUE TITLE
Missing sample for Ajax handling.

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-arch#30]
We could find an echo server online and simply show an ajax call to the server to demonstrate ajax support.

Just posting this one here: http://ivanzuzak.info/urlecho/

Example of url: [http://urlecho.appspot.com/echo?status=200&Content-Type=text%2Fhtml&body=Hello%20world!](http://urlecho.appspot.com/echo?status=200&Content-Type=text%2Fhtml&body=Hello%20world!)

**Comment by mastoj** [comment]
:+1: this is definitely something we need.

**Comment by tforkmann** [comment]
If I get it implemented in my app. Then I would like to help you guys.

**Comment by MangelMaxime** [comment]
If everything goes well. I will publish the sample today :)
