### ISSUE TITLE
Implement renderer for react

### ISSUE THREAD

**Issue by mastoj** [fable-compiler/fable-arch#33]
Now when the implementation is 100% decoupled we should add a renderer for react as well.

**Comment by jmmk** [comment]
Does [Fable.Arch.React.fs](https://github.com/fable-compiler/fable-arch/blob/master/src/Fable.Arch/Fable.Arch.React.fs) complete this issue?

**Comment by mastoj** [comment]
I definitely completes a first rough version. @jmmk

**Comment by fsoikin** [comment]
Do I understand it correctly that there is no `View.map` support yet?

**Comment by mastoj** [comment]
There is a Html.map, is that what you think of?

**Comment by fsoikin** [comment]
That works for "regular" view.
What about React view?

**Comment by mastoj** [comment]
You're right, it doesn't exist for react. It shouldn't be too hard to implement though.
