### ISSUE TITLE
DevTools messing up the state

### ISSUE THREAD

**Issue by mastoj** [fable-compiler/fable-arch#39]
Doing a couple of increments on the top counter followed by a commit, a couple of increment on the bottom counter and then toggling those events will result in the incorrect model. Test here: https://fable-compiler.github.io/fable-arch/samples/plugin/index.html

**Comment by MangelMaxime** [comment]
I can't reproduce it.

**Comment by MangelMaxime** [comment]
Should be closed ? @mastoj

**Comment by mastoj** [comment]
Yes. I thought it was :)
