### ISSUE TITLE
What view engine is used?

### ISSUE THREAD

**Issue by Biarity** [fable-compiler/fable-arch#47]
Does this use React like fable-elmish, and if not, how is it different from it?

**Comment by MangelMaxime** [comment]
Hello, 
fable-arch is now not linked to a specific renderer, you can use any renderer you want as long you tell fable-arch how to use it.

We currently have 2 renderer supported:
- React
- VirtualDom

The most commonly is with fable-arch is VirtualDom but it's just a matter of personnal choice.

You can see [here](http://fable.io/fable-arch/) samples.
All of them are using VirtualDom except the last one which use React.

@mastoj Will be probably give you a better explanation.
