### ISSUE TITLE
Upgrade to 0.7

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-arch#48]
Hi @mastoj  and @MangelMaxime!

I've upgraded fable-arch to Fable 0.7, you can see the result in `0.7.0` branch. At the very least the React sample is working. You can try doing the following:

- In repo root:
```
git checkout 0.7.0
npm i
node build
```

- In `samples/react/` dir:
```
npm run build
npm start
```

I must say fable-arch looks very neat, but the lack of comments and type annotations make it a bit difficult to follow. I tried to simplify the architecture for React, but I wasn't able because after many tries I couldn't understand the flow of the app. In any case the app works as it's now 😄  At the beginning I had the wrong impression the component was mounted multiple times or that `setState` was called twice every time, but after debugging the sample. It doesn't seem to be the case.

**Comment by MangelMaxime** [comment]
That's really cool :)

And yes documentation is something planned and needed :)
We was waiting to finish the rewrite fable-arch, and I think it's probably a good time to add the documentation now.
I should have some time next week to work on it.

**Comment by alfonsogarciacaro** [comment]
Great! Before documentation, I think type annotations in Fable.Arch.App are important, mainly because the automatic generics when checking code lenses in Ionide, for example, are not very meaningful (`('a->'c->'a)->('c->unit)`).

**Comment by MangelMaxime** [comment]
Oh yes, this something I am included in documentation :)
And this should also help us, giving definition like whats is an handler ? a message ? etc.
Helping to communicate more easily with new comers.

**Comment by alfonsogarciacaro** [comment]
Should I send a PR for this? :)

**Comment by MangelMaxime** [comment]
If you want to give it a try yes.
Like that we can review the type names inside the PR :)
