### ISSUE TITLE
Todomvc sample - missing file?

### ISSUE THREAD

**Issue by markpattison** [fable-compiler/fable-arch#60]
Sorry if this is a silly question...

At line 6 in [this file](https://github.com/fable-compiler/fable-arch/blob/master/samples/todomvc/index.html) in the Todomvc sample, it refers to a file "./public/index.css".

I can't see where this file comes from - it isn't in the sample, and it isn't being generated by fable or webpack.

**Comment by Zaid-Ajaj** [comment]
@markpattison this file gets generated (or atleast copied from node_modules) when you `npm run build`.

 Take a look at [package.json](https://github.com/fable-compiler/fable-arch/blob/master/samples/todomvc/package.json#L6)

**Comment by markpattison** [comment]
Thanks for your help!
