### ISSUE TITLE
Should we start removing samples which are not in line with current Fable-arch api?

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/fable-arch#62]
withNavigation is removed from App.AppApi so sample should be removed or changed? There may be chance that other samples also needed to removed so if that is OK I ll PR them or just list out here.

**Comment by MangelMaxime** [comment]
I planned to do a pass on all the samples when the docs sites update is available.
Doing this pass, I will clean the samples, and migrate the sample to use the latest version of Fable-arch and also have a compliant styling using Bulma where it make sense :)

**Comment by kunjee17** [comment]
Cool. I'm closing this for now then... Thanks. 👌
