### ISSUE TITLE
Support dispatching messages from a hook to main app

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/fable-arch#70]
Continuing on with the discussion and proposals in #67 

This would enable us writing custom view _components_* that are able to dispatch/send messages back to the app disptach loop.

Example code of how this would look like  (notice the `(dispatch: 't -> unit)` parameter) 
```fsharp
type Messages =
    | Clicked 
```
```fsharp
div 
  [ hook 
      "my-hook"
      (HookHelper.CreateHook(fun node propName (dispatch: 't -> unit) -> 
              node.addEventListener("click", fun () -> dispatch Click)
      ))
  ] [ text "I dispatch 'Click' messages" ]
```
I would say that the `hook` function should be hidden away some module like `Fable.Arch.Internal` as this shouldn't be used by the end user but only but implementers who write these custom components because otherwise we are breaking the whole Elm architecture by introducing side effects (playing with the DOM directly)

What do you guys think?

_components_: in the sense of a stateless component that has custom props and custom inner behaviour hidden from the user.

**Comment by codec-abc** [comment]
As am I really as beginner I can really give sensible advice on the matter but at least I can detail my own use case about the hook function. Beside the reason to use it given in the issue #67 I found another use of the hook function. In my app I used a slider and a range input to update the same underlying model (and so the view too). I did reproduce the issue with [Elm](https://ellie-app.com/v3HGgh8cyra1/0). In that sample, if you start to play with the input and the range alternatively they go out of sync. So my use case for the hook function probably come from a bad design decision (in the UI/UX sense) but still the hook function allowed me to make my app working easily. Bottom line, I used the hook function for at least 2 things in a little app as such it may be better to let the end user use it but advise against its use in the documentation.
